# Main build settings
[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

# Environment settings for the build
[build.environment]
  NODE_VERSION = "18"

# Configuration for your serverless functions
[functions]
  # This increases the timeout from 10 seconds to 25 seconds.
  timeout = 25
