[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# This is the correct syntax to apply a setting to all functions.
# It gives them more memory and CPU power to prevent timeouts.
[functions."*"]
  memory = 2048
